# This is a basic workflow that is manually triggered

name: Create Release Branch

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      releaseNumber:
        description: 'Release branch verion (ex 27.1)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create-branch"
  create-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch from development
      run: git checkout -b release-${{ github.event.inputs.releaseNumber }} development
    - name: Push new release branch
      run: git push origin release-${{ github.event.inputs.releaseNumber }}
