# This is a basic workflow that is manually triggered

name: Uptick Version Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    inputs:
      current:
        description: 'Current version (pom.xml and Jenkins)'
        required: true
      new:
        description: 'New version (pom.xml and Jenkins)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "uptick-version"
  uptick-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 1. Check out code
      uses: actions/checkout@v2
    - name: 2. Create uptick branch from development
      run: git checkout -b uptick-${{ github.event.inputs.new }} development
    - name: 3a. Find and Replace 'current' with 'new' in pom.xml files
      run: |
        find . -type f -name 'pom.xml' -exec sed -i 's/${{ github.event.inputs.current }}-SNAPSHOT/${{ github.event.inputs.new }}-SNAPSHOT/g' {} +
    - name: 3b. Find and Replace 'current' with 'new' in Jenkinsfile
      run: |
        find . -type f -name 'Jenkinsfile' -exec sed -i 's/releaseId = "${{ github.event.inputs.current }}"/releaseId = "${{ github.event.inputs.new }}"/g' {} +
    - name: 4. Commit and push uptick branch
      run: |
        git config user.name '${GITHUB_ACTOR}'
        git config user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git commit -am 'Uptick repo from ${{ github.event.inputs.current }} to ${{ github.event.inputs.new }}'
        git push origin uptick-${{ github.event.inputs.new }}
    - name: 5. Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: uptick-${{ github.event.inputs.new }}
          base: development
          title: ${{ github.event.inputs.new }} into development
          reviewers: ${GITHUB_ACTOR}
          body: |
              Hi Human!
              This PR was created in response to a workflow running - 
              pom.xml and Jenkinsfile updated from ${{ github.event.inputs.current }} to ${{ github.event.inputs.new }}.

